language: node_js
node_js:
- v6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
script:
  - npm test -- -i --coverage
env:
  global:
  - CXX=g++-4.8
  - MASTER_KEY=masterKey
deploy:
  provider: heroku
  api_key: 795125dd-22d1-4843-86db-e4c187a724a2
  app:
    dev: exchange-stat
